/**
 * @fileoverview Configuration for crime command
 * @module config/commands/crime
 */

export default {
  COOLDOWN_KEY: 'crimeCooldownUntil',
  ACTION_COOLDOWN_SECONDS: 420, // 7 minutes
  SELECTION_TIMEOUT_MS: 25000,
  CHOICES_PER_RUN: 3,
  DEATH_LOSS_MIN_PERCENT: 25,
  DEATH_LOSS_MAX_PERCENT: 75,
  SCALING: {
    BALANCE_PIVOT: 9000,
    BALANCE_CURVE_POWER: 0.88,
    BALANCE_MIN_MULT_BPS: 6000, // 0.60x at very low balance
    BALANCE_MAX_MULT_BPS: 24000, // 2.40x wealth scaling cap (before level)
    LEVEL_BONUS_BPS_PER_LEVEL: 120, // +1.20% per level
    LEVEL_BONUS_MAX_BPS: 9000, // +90% max from level
    GLOBAL_MAX_MULT_BPS: 34000, // absolute cap: 3.40x
    REWARD_CAP_BASE: 220, // fixed cap cushion
    REWARD_BALANCE_CAP_BPS: 60, // +0.60% of total balance
  },
  CRIMES: [
    {
      id: 'pickpocket',
      label: 'Pickpocket',
      emoji: '🧤',
      rewardMin: 25,
      rewardMax: 65,
      failChanceBps: 3600,
      deathChanceBps: 150,
      fineMinPercent: 4,
      fineMaxPercent: 12,
      siteText: 'You blend into a packed night market crowd.',
      actionText: 'You brush past your target and go for the wallet...',
      successText: 'Clean lift. Nobody noticed.',
      failText: 'You got spotted and had to pay your way out.',
      deathText: 'A violent guard reacted before you could escape.',
    },
    {
      id: 'shoplift',
      label: 'Shoplift',
      emoji: '🛍️',
      rewardMin: 35,
      rewardMax: 90,
      failChanceBps: 3900,
      deathChanceBps: 200,
      fineMinPercent: 5,
      fineMaxPercent: 13,
      siteText: 'You stroll through a luxury convenience store.',
      actionText: 'You slip high-value goods into a hidden pouch...',
      successText: 'You fenced the goods fast for cash.',
      failText: 'Store security caught you near the exit.',
      deathText: 'A confrontation turned deadly inside the store.',
    },
    {
      id: 'porch_pirate',
      label: 'Porch Pirate',
      emoji: '📦',
      rewardMin: 45,
      rewardMax: 110,
      failChanceBps: 4100,
      deathChanceBps: 250,
      fineMinPercent: 6,
      fineMaxPercent: 14,
      siteText: 'You scan suburban porches for fresh deliveries.',
      actionText: 'You sprint in, snatch boxes, and jump the fence...',
      successText: 'Most boxes had resale value.',
      failText: 'Neighbors flagged you and patrol arrived.',
      deathText: 'An armed homeowner confronted you.',
    },
    {
      id: 'atm_skimmer',
      label: 'ATM Skimmer',
      emoji: '🏧',
      rewardMin: 80,
      rewardMax: 190,
      failChanceBps: 4300,
      deathChanceBps: 350,
      fineMinPercent: 8,
      fineMaxPercent: 18,
      siteText: 'You choose an old ATM with poor camera angles.',
      actionText: 'You mount the skimmer and wait for data hits...',
      successText: 'You sold the card dump for good money.',
      failText: 'A tech team traced the device to you.',
      deathText: 'You were caught in a violent takedown.',
    },
    {
      id: 'catalytic_theft',
      label: 'Catalytic Theft',
      emoji: '🔧',
      rewardMin: 95,
      rewardMax: 220,
      failChanceBps: 4400,
      deathChanceBps: 400,
      fineMinPercent: 8,
      fineMaxPercent: 20,
      siteText: 'You scout a quiet parking lot before dawn.',
      actionText: 'You slide under a car and start cutting metal...',
      successText: 'Scrap buyers paid quickly.',
      failText: 'Alarm systems and cameras burned you.',
      deathText: 'A jack slipped and crushed you during the theft.',
    },
    {
      id: 'carjack',
      label: 'Carjack',
      emoji: '🚗',
      rewardMin: 140,
      rewardMax: 320,
      failChanceBps: 4600,
      deathChanceBps: 550,
      fineMinPercent: 10,
      fineMaxPercent: 24,
      siteText: 'You trail an expensive car into a dead-end street.',
      actionText: 'You move fast and force the driver out...',
      successText: 'The chop shop transfer went through.',
      failText: 'You were intercepted before the handoff.',
      deathText: 'The attempt escalated into lethal violence.',
    },
    {
      id: 'warehouse_raid',
      label: 'Warehouse Raid',
      emoji: '🏚️',
      rewardMin: 180,
      rewardMax: 420,
      failChanceBps: 4800,
      deathChanceBps: 700,
      fineMinPercent: 12,
      fineMaxPercent: 26,
      siteText: 'You cut power to an old storage warehouse.',
      actionText: 'You crack open crates and load whatever moves...',
      successText: 'You offloaded stolen stock at a discount.',
      failText: 'A silent alarm locked the building down.',
      deathText: 'A structural collapse buried you during the raid.',
    },
    {
      id: 'identity_fraud',
      label: 'Identity Fraud',
      emoji: '🪪',
      rewardMin: 210,
      rewardMax: 480,
      failChanceBps: 5000,
      deathChanceBps: 750,
      fineMinPercent: 12,
      fineMaxPercent: 30,
      siteText: 'You buy leaked records from a dark web forum.',
      actionText: 'You run synthetic identities through payment rails...',
      successText: 'The fraud cycle cleared before chargebacks hit.',
      failText: 'Risk controls froze everything and traced you.',
      deathText: 'You crossed the wrong people while laundering data.',
    },
    {
      id: 'jewelry_heist',
      label: 'Jewelry Heist',
      emoji: '💎',
      rewardMin: 260,
      rewardMax: 620,
      failChanceBps: 5200,
      deathChanceBps: 900,
      fineMinPercent: 14,
      fineMaxPercent: 32,
      siteText: 'You case a jewelry store during shift change.',
      actionText: 'You smash display locks and fill your bag...',
      successText: 'A private buyer paid premium for the stones.',
      failText: 'You got trapped between shutters and police.',
      deathText: 'Gunfire erupted during your escape.',
    },
    {
      id: 'armored_van',
      label: 'Armored Van Hit',
      emoji: '🚚',
      rewardMin: 320,
      rewardMax: 760,
      failChanceBps: 5500,
      deathChanceBps: 1100,
      fineMinPercent: 16,
      fineMaxPercent: 36,
      siteText: 'You track an armored route through back streets.',
      actionText: 'You block the lane and breach the cargo lock...',
      successText: 'The cash split was worth the risk.',
      failText: 'Response teams boxed you in immediately.',
      deathText: 'The firefight left no way out.',
    },
    {
      id: 'casino_chip_scam',
      label: 'Casino Chip Scam',
      emoji: '🎰',
      rewardMin: 360,
      rewardMax: 820,
      failChanceBps: 5600,
      deathChanceBps: 1200,
      fineMinPercent: 16,
      fineMaxPercent: 36,
      siteText: 'You infiltrate a high-traffic casino floor.',
      actionText: 'You swap counterfeit chips into circulation...',
      successText: 'You cashed out before surveillance flagged you.',
      failText: 'Security isolated you and confiscated everything.',
      deathText: 'Enforcers cornered you in a service corridor.',
    },
    {
      id: 'museum_heist',
      label: 'Museum Heist',
      emoji: '🖼️',
      rewardMin: 420,
      rewardMax: 980,
      failChanceBps: 5900,
      deathChanceBps: 1400,
      fineMinPercent: 18,
      fineMaxPercent: 40,
      siteText: 'You enter a museum after-hours through maintenance.',
      actionText: 'You cut lasers and lift a marked piece...',
      successText: 'A collector wired payment with no questions asked.',
      failText: 'Motion tracking systems immediately pinned you.',
      deathText: 'A failed escape route ended the job permanently.',
    },
    {
      id: 'yacht_smuggling',
      label: 'Yacht Smuggling',
      emoji: '🛥️',
      rewardMin: 500,
      rewardMax: 1180,
      failChanceBps: 6200,
      deathChanceBps: 1600,
      fineMinPercent: 20,
      fineMaxPercent: 44,
      siteText: 'You rendezvous with a yacht beyond harbor cameras.',
      actionText: 'You move contraband through a midnight channel...',
      successText: 'The delivery paid big and fast.',
      failText: 'Coast patrol seized the shipment and your cut.',
      deathText: 'A violent chase sank the operation.',
    },
    {
      id: 'data_center_extortion',
      label: 'Data Center Extortion',
      emoji: '🖥️',
      rewardMin: 580,
      rewardMax: 1320,
      failChanceBps: 6400,
      deathChanceBps: 1700,
      fineMinPercent: 20,
      fineMaxPercent: 45,
      siteText: 'You breach a legacy data center through an exposed node.',
      actionText: 'You deploy ransomware and demand a payment window...',
      successText: 'The victim paid to restore operations.',
      failText: 'Incident response teams traced and neutralized you.',
      deathText: 'Retaliation from a syndicate ended the play.',
    },
    {
      id: 'bank_tunnel',
      label: 'Bank Tunnel',
      emoji: '🏦',
      rewardMin: 700,
      rewardMax: 1600,
      failChanceBps: 6800,
      deathChanceBps: 2000,
      fineMinPercent: 22,
      fineMaxPercent: 48,
      siteText: 'You spend nights digging toward a bank vault wall.',
      actionText: 'You break through and rush to clear lockboxes...',
      successText: 'Huge score. You vanished before dawn.',
      failText: 'Tunnel sensors caught the breach in real time.',
      deathText: 'The tunnel collapsed before you made it out.',
    },
  ],
};
